### ISSUE TITLE
请问ubuntu下怎样使用？

### ISSUE THREAD

**Issue by FatBobGo** [zzzzbw/gitPic#1]
我已经安装好java。但是运行的时候报错。

```bash
inspiron:~/software$ java -version 
openjdk version "11.0.1" 2018-10-16  
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-2ubuntu1)  
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-2ubuntu1, mixed mode, sharing)
```

报错信息

```bash
inspiron:~/software$ java gitPic-java.jar
错误: 找不到或无法加载主类 gitPic-java.jar
原因: java.lang.ClassNotFoundException: gitPic-java.jar
```

```bash
inspiron:~/software$ java -jar gitPic-java.jar 
错误: 找不到或无法加载主类 com.zbw.gitpic.Bootstrap
原因: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by zzzzbw** [comment]
你安装的java是11, java11里面去除了自带的javafx. 你需要另外安装javafx的jdk或者更改环境为java8

**Comment by FatBobGo** [comment]
@zzzzbw 谢谢。我尝试了安装javafx（下载包，然后export环境变量），还是不行。
然后我通过`apt get install openjdk8`安装java8，但是不知道怎样调用。
请问你有详细一点的教程吗？

**Comment by zzzzbw** [comment]
你这是java环境的问题，虽然后面安装了java8，但是应该环境变量没设置过去，你`java -version `看看应该还是java11。java8的安装和环境变量你可以看看这篇https://blog.csdn.net/sangewuxie/article/details/80958611

**Comment by FatBobGo** [comment]
不好意思，又遇到错误了。你知道为什么这个jar没有包含需要的包吗？
我自己下载了 **bootstrap.jar** 放到 `/usr/local/sbin`   但是好像不起作用
```
[bob@ /home/bob/software] java -jar gitPic-java.jar 
错误: 找不到或无法加载主类 com.zbw.gitpic.Bootstrap
```

**Comment by zzzzbw** [comment]
你这个bootstrap.jar是什么的jar包

**Comment by zzzzbw** [comment]
@FatBobGo 已经增加对java11的支持，有问题欢迎反馈！

**Comment by zheng-xing** [comment]
我在 MAC 上也碰到这了个错误。

> $ java -version
> openjdk version "1.8.0_112-release"
> OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
> OpenJDK 64-Bit Server VM (build 25.112-b06, mixed mode)

> $ java -jar gitPic-java.jar
> Error: Could not find or load main class com.zbw.gitpic.Bootstrap


请问 @FatBobGo @zzzzbw 有好的解决办法吗？谢谢。

**Comment by zzzzbw** [comment]
@zheng-xing 
你是不是下的java11的版本，java8的这里[下载](https://github.com/zzzzbw/gitPic/issues/1#issuecomment-570810519)

**Comment by zheng-xing** [comment]
> @zheng-xing
> 你是不是下的java11的版本，java8的这里[下载](https://github.com/zzzzbw/gitPic/issues/1#issuecomment-570810519)

我下载的就是[这里](https://github.com/zzzzbw/gitPic/releases/tag/v0.1-java8)的java8的版本，是不是只下载那个 jar 文件就行？

**Comment by zzzzbw** [comment]
@zheng-xing 
你用的是OpenJDK，OpenJDK8并不像OracleJDK8那样包含OpenJFX。
* 如果让OpenJDK8也能使用OpenJFX需要自己手动编译一下。这篇可以参考一下[Centos7编译并整合OpenJDK8和OpenJFX](https://blog.csdn.net/huangdeijia/article/details/79445046)。
* 或者改使用Oracle的JDK8。
* 或者升级为OpenJDK 11，并使用gitPic java11版本

**Comment by zheng-xing** [comment]
> @zheng-xing
> 你用的是OpenJDK，OpenJDK8并不像OracleJDK8那样包含OpenJFX。
> 
> * 如果让OpenJDK8也能使用OpenJFX需要自己手动编译一下。这篇可以参考一下[Centos7编译并整合OpenJDK8和OpenJFX](https://blog.csdn.net/huangdeijia/article/details/79445046)。
> * 或者改使用Oracle的JDK8。
> * 或者升级为OpenJDK 11，并使用gitPic java11版本

非常感谢回复！
在 [AdoptOpenJDK](https://adoptopenjdk.net/index.html?variant=openjdk11&jvmVariant=hotspot) 下载了 OpenJDK 11，然后问题解决了！
