### ISSUE TITLE
请问现在支持截图之后直接张贴吗

### ISSUE THREAD

**Issue by gdutxiaoxu** [zzzzbw/gitPic#2]
现在功能已经做得非常 nice 了，如果能支持截图之后张贴，那就更不错了。支持一个先，star。

**Comment by gdutxiaoxu** [comment]
你好，请问你这个是用哪个 ide 开发的，我用 eclipse 导入你的项目一直找不到

**Comment by zzzzbw** [comment]
@gdutxiaoxu 
用 jetbrains 的 idea，如果要用 eclipse 的话要从 Existing Maven Projects 导入

**Comment by gdutxiaoxu** [comment]
好的，非常感谢 @zzzzbw

**Comment by zzzzbw** [comment]
[v0.2](https://github.com/zzzzbw/gitPic/releases/tag/v0.2)新增剪切板上传
