### ISSUE TITLE
git push异常，权限不够

### ISSUE THREAD

**Issue by codershenghai** [zzzzbw/gitPic#3]
您好，请问点击提交并上传之后显示：

git push异常，message:git@github.com:shenghaishxt/hexo_images.git: Auth fail异常是什么原因导致的呢？

项目是用SSH克隆到本地的，这些都已经认证过了。

**Comment by zzzzbw** [comment]
是不是你本地的git环境没设置完。
你有在本地push过项目吗

**Comment by codershenghai** [comment]
@zzzzbw  有，push没问题，很奇怪。

**Comment by zzzzbw** [comment]
请问你是用的jar包运行的还是源码运行的。
能够提供更详细的错误信息
